# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf1e30e99d02c01f2db87031cf9ba540ba70e1495e51baba985debbd1b12548de44437472552333869269421f0ec98fb5a110091b9b48848399696b047580c46

test:
  secret_key_base: 71ab444f2e2ad66697667d74945ad4a4bef5df006df79ff100606fafe7f9a07f08779e438732b2688c065198cef69ce9fbe6ea58b18bc6207ddfeca95526860f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
